### ISSUE TITLE
Hi, where does the score function come from ?

### ISSUE THREAD

**Issue by chenxianwang** [NicolasHug/nicolashug.github.io#1]
Hi, where does the score function come from ?

I do not see a definition in the BaseGradientBoosting class and the Classification/Regression Class.

Thanks.

**Comment by chenxianwang** [comment]
I mean in the assets/gradient_boosting_descent notebook. Thanks.

**Comment by NicolasHug** [comment]
They come from the scikit-learn mixins e.g. https://scikit-learn.org/stable/modules/generated/sklearn.base.RegressorMixin.html

**Comment by chenxianwang** [comment]
Great. Thanks for your pretty nice work.
