### ISSUE TITLE
AttributeError: 'DatasetAutoFolds' object has no attribute 'split'

### ISSUE THREAD

**Issue by stevewalker-de** [NicolasHug/nicolashug.github.io#2]
![surprise](https://user-images.githubusercontent.com/67876607/89443969-a4103780-d716-11ea-9fbd-0a9c2f8d6220.png)

**Comment by NicolasHug** [comment]
Use CV iterators instead of calling `split` which is not supported anymore: https://surprise.readthedocs.io/en/stable/getting_started.html#use-cross-validation-iterators

**Comment by stevewalker-de** [comment]
Thanks for the quick response.  That worked great.  Shall I attach an updated notebook for you to repost?

**Comment by NicolasHug** [comment]
Ah I always forget to update the notebooks... Sorry about that and thanks for the report

Thanks for the proposal, since notebooks are pretty hard to review it will be faster if I just udpate it myself ;)

**Comment by stevewalker-de** [comment]
okie dokie.  Standing by.....


Steve Walker

Google Cloud Specialist Customer Engineer, AI/ML, Analytics

209-602-5288 Mobile

Google Cloud Certified Data Engineer
<https://www.credential.net/0dbf9eab-d5fa-48bc-8622-54464e2f73aa?key=ec440b3ebf612c25b0f058434c6771643248d5da344b20a9bc36e2f9ffe02cd6>

**Comment by NicolasHug** [comment]
Just pushed the new notebooks

https://github.com/NicolasHug/Surprise/blob/master/examples/notebooks/KNNBasic_analysis.ipynb
https://github.com/NicolasHug/Surprise/blob/master/examples/notebooks/Compare.ipynb

It might take a little for nbviewer's cache to be updated  though
